import Head from "next/head";

import Layout from "../components/Layout/layout";
import Header from '../components/Header/index';
import Contact from "../components/Contact";

// markup
const ContactPage = () => {
  return (
    <>
      <Head>
        <title>Contactez développeuse web Morgane Tressens</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <Header />
        
        <Contact />
      </Layout>

    </>
  )
}

export default ContactPage;
