import Head from "next/head";

import Layout from "../components/Layout/layout";
import Header from '../components/Header/index';

// markup
const CvPage = () => {
  return (
    <>
      <Head>
        <title>Profil compétences Morgane Tressens</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <Header />
        <h1>page CV</h1>

      </Layout>

    </>
  )
}

export default CvPage;
