import Head from 'next/head';

import Layout from '../components/Layout/layout';
import Home from '../components/Home';

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Portfolio Morgane Tressens</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <Home />
      </Layout>

    </>
  )
};
