import Head from "next/head";

import Layout from "../components/Layout/layout";
import Header from '../components/Header/index';
import Profil from "../components/Profil";

// markup
const ProfilPage = () => {
  return (
    <>
      <Head>
        <title>Profil et compétences Morgane Tressens</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <Header />
        <h1>Mon profil</h1>
        <Profil />
      </Layout>

    </>
  )
}

export default ProfilPage;
