import Head from "next/head";

import Layout from "../components/Layout/layout";
import Header from '../components/Header/index';
import CardTech from "../components/CardTech";

import data from '../data';

// markup
const TechnoPage = () => {
  return (
    <>
      <Head>
        <title>Les technologies maîtrisées dans le développement web</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <Header />
        <CardTech dataTechno={data} />
      </Layout>

    </>
  )
}
export default TechnoPage;
