import Head from "next/head";

import Layout from "../components/Layout/layout";
import Header from '../components/Header/index';

// markup
const TechnoPage = () => {
  return (
    <>
      <Head>
        <title>Les technologies maîtrisées dans le développement web</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
      <Header />
        <h1>page techno</h1>
        <ul>
          <li>HTML</li>
          <li>CSS / SCSS</li>
          <li>Javascript</li>
          <li>React</li>
          <li>Nextjs</li>
          <li>PHP</li>
          <li>Symfony</li>
          <li>MySQL</li>
          <li>GitHub</li>
        </ul>
   
      </Layout>

    </>
  )
}

export default TechnoPage;
